name: "Setup Git Committer"
description: "Configure git user"
runs:
  using: "composite"
  steps:
    - name: Configure git user
      run: |
        git config --global user.name "MLXProjects"
        git config --global user.email "mlx@projec.ts"
      shell: bash
